services:
  front:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    command: sh -c "npm run dev"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WATCHPACK_POLLING=true
    depends_on:
      - db
    volumes:
      - .:/app
      - nestjs-node-modules:/workspace/node_modules

  db:
    image: postgres:14
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  nestjs-node-modules: